package com.chrynan.presentation.resources

enum class StringIds : StringResourceIdentifier {

    APP_NAME,
    MENU_BOTTOM_NAVIGATION_HOME,
    MENU_BOTTOM_NAVIGATION_SEARCH,
    MENU_BOTTOM_NAVIGATION_USER_CONTENT,
    MENU_BOTTOM_NAVIGATION_SETTINGS,
    MENU_VIDEO_DISMISS,
    MENU_VIDEO_SHARE,
    MENU_VIDEO_REPORT,
    MENU_VIDEO_PLAY_NOW,
    MENU_VIDEO_PLAY_NEXT,
    MENU_VIDEO_ADD_TO_QUEUE,
    MENU_VIDEO_ADD_TO_WATCH_LIST,
    MENU_VIDEO_QUEUE_REMOVE_FROM_QUEUE,
    MENU_VIDEO_QUEUE_ADD_TO_WATCH_LIST,
    MENU_VIDEO_QUEUE_SHARE,
    VIDEO_INFO_BUTTON_LIKE,
    VIDEO_INFO_BUTTON_DISLIKE,
    VIDEO_INFO_BUTTON_SHARE,
    VIDEO_INFO_BUTTON_SUBSCRIBE,
    VIDEO_INFO_BUTTON_UNSUBSCRIBE,
    VIDEO_INFO_SUBTITLE_PUBLISHED,
    VIDEO_INFO_SUBTITLE_CATEGORY,
    VIDEO_INFO_SUBTITLE_TAGS,
    VIDEO_INFO_SUBTITLE_PROVIDER,
    CHANNEL_INFO_HEADER_ABOUT,
    CHANNEL_INFO_SUBTITLE_CREATED,
    CHANNEL_INFO_SUBTITLE_LAST_UPDATED,
    SEARCH_HINT;

    override val id = name.toLowerCase()
}